
export const RTB_SUBJECTS = [
    "Accounting",
    "Animal Husbandry",
    "App Security",
    "Automotive Technology",
    "Civil Engineering",
    "Cosmetology",
    "Crop Production",
    "Culinary Arts",
    "Electrical Engineering",
    "Electronics & Telecommunication",
    "Entrepreneurship",
    "Food Technology",
    "Hotel Management",
    "HVAC-R Technology",
    "Information & Communication Technology (ICT)",
    "Laboratory Technology",
    "Machining & Manufacturing",
    "Mechanical Engineering",
    "Multimedia & Animation",
    "Networking & System Administration",
    "Nursing",
    "Office Management",
    "Pharmacy",
    "Plumbing",
    "RTB",
    "Software Development",
    "Tour Guiding",
    "Welding Technology",
];

export const REB_SUBJECTS = [
    "BCG (Biology – Chemistry – Geography)",
    "General Mathematics",
    "General Science",
    "Geography",
    "HEG (History – Economics – Geography)",
    "HEL (History – Economics – Literature in English)",
    "HGL (History – Geography – Literature in English)",
    "LEG (Literature in English – Economics – Geography)",
    "LFK (Literature in English – French – Kinyarwanda)",
    "LKF (Literature in English – Kiswahili – French)",
    "LKK (Literature in English – Kiswahili – Kinyarwanda)",
    "MCB (Mathematics – Chemistry – Biology)",
    "MCE (Mathematics – Computer Science – Economics)",
    "MEG (Mathematics – Economics – Geography)",
    "MPC (Mathematics – Physics – Computer Science)",
    "PCB (Physics – Chemistry – Biology)",
    "PCM (Physics – Chemistry – Mathematics)",
    "REGL (Religious Education – Geography – Literature in English)",
    "REHL (Religious Education – History – Literature in English)",
];